#9 Pytorchlightning
FHOOEAIST/aist-kube-stacks pull request #10
Opened 2021-05-18 12:46 UTC by oliver-krauss

The only thing we actually needed was a newer version of cuda

2021-05-18 12:53 UTC, 2er0 approved these changes

2021-05-19 06:12 UTC, pointan approved these changes

2021-05-19 06:13 UTC, pointan requested changes
Hmm, the code itself looks good, but I dislike, that you did not include a ticket-number in the commit.

2021-05-20 06:26 UTC, pointan approved these changes

2021-05-20 06:26 UTC, merged